---
title: Presentaciones de Análisis Matemático de Variable Real
format: 
    html:
        theme:
            dark: [darkly, custom-dark.scss]
            light: [flatly, custom.scss]
lang: es
---

Presentaciones del [manual de Análisis Matemático de Variable Real](https://aprendeconalf.es/analisis-manual/).

1. [Introducción](01-introduccion.html).

1. [Estadística descriptiva](02-estadistica-descriptiva.html).

1. [Regresión y correlación](03-regresion.html).

1. [Probabilidad](04-probabilidad.html).

1. [Variables aleatorias discretas](05-variables-aleatorias-discretas.html).

1. [Variables aleatorias continuas](06-variables-aleatorias-continuas.html).

1. [Estimación de parámetros poblacionales](07-estimacion.html).

1. [Contrastes de hipótesis paramétricos](08-contrastes-parametricos.html).

1. [Contrastes de hipótesis no paramétricos](09-contrastes-no-parametricos.html).

## Licencia

Esta obra está bajo una licencia Reconocimiento – No comercial – Compartir bajo la misma licencia 3.0 España de Creative Commons. Para ver una copia de esta licencia, visite [https://creativecommons.org/licenses/by-nc-sa/3.0/es/](https://creativecommons.org/licenses/by-nc-sa/3.0/es/).

Con esta licencia eres libre de:

- Copiar, distribuir y mostrar este trabajo.
- Realizar modificaciones de este trabajo.

Bajo las siguientes condiciones:

- **Reconocimiento**. Debe reconocer los créditos de la obra de la manera especificada por el autor o el licenciador (pero no de una manera que sugiera que tiene su apoyo o apoyan el uso que hace de su obra).

- **No comercial**. No puede utilizar esta obra para fines comerciales.

- **Compartir bajo la misma licencia**. Si altera o transforma esta obra, o genera una obra derivada, sólo puede distribuir la obra generada bajo una licencia idéntica a ésta.

Al reutilizar o distribuir la obra, tiene que dejar bien claro los términos de la licencia de esta obra.

Estas condiciones pueden no aplicarse si se obtiene el permiso del titular de los derechos de autor.

Nada en esta licencia menoscaba o restringe los derechos morales del autor.
